QOI Support, attempt 2
image-rs/image pull request #1824
Opened 2022-11-15 06:18 UTC by mattfbacon

License consent as usual. I fixed the issues described in the initial PR.

Backreference: #1780

2022-11-15 19:44 UTC, HeroicKatora requested changes
That's my only remaining concern here.

2022-11-15 19:44 UTC, HeroicKatora commented on src/codecs/qoi.rs
> +        _color_type: ColorType,
This one is still open.

> Ignoring color isn't correct here. Rather, QOI supports only 8-bit rgb-ish color (with optional colorspace). We'll want to either convert here, or raise on error on unsupported formats.


https://github.com/image-rs/image/pull/1780#discussion_r960338581

2022-11-15 23:50 UTC, mattfbacon commented
Fixed

2022-11-16 12:43 UTC, HeroicKatora approved these changes

2022-11-16 12:44 UTC, merged